config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get "search" => "searches#search"
  
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers' 
  end
    resources :messages, only: [:create]
    resources :rooms, only: [:create,:show]
  
  resources :books do
    # resourceにすると、そのコントローラのidがリクエストに含まれなくなる。
    # favoritesのshowページが不要で、idの受け渡しも必要ないので、resourceとなる
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
    get 'category'
  end
  
end

app/models/book.rb
class Book < ApplicationRecord
	
	belongs_to :user
	
	# dependent: :destroy 親モデルを削除する際に、その親モデルに紐づく「子モデル」も一緒に削除できる
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user
	has_many :book_comments, dependent: :destroy
	
	has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
	
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	validates :rate, presence: true
	
  # favorited_by?メソッド 
  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べます。
  # 存在していればtrue、存在していなければfalseを返すようにしています。
	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.looks(search, word)
    if search == "perfect"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward"
      @book = Book.where("title LIKE?","%#{word}")
    else search == "partia"
      @book = Book.where("title LIKE?","%#{word}%")
    end
  end
  
  def save_tag(sent_tags)
    if self.tags != nil
      article_tags_records = ArticleTag.where(article_id: self.id)
      article_tags_records.destroy_all
    end

    tag_list.each do |tag|
      inspected_tag = Tag.where(tag_name: tag).first_or_create
      self.book_tags << inspected_tag
    end
  end
  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    if params[:sort]
      @books = Book.all.order(params[:sort])
    else
      to  = Time.current.at_end_of_day
      from  = (to - 6.day).at_beginning_of_day
      @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.where(created_at: from...to).size <=> a.favorited_users.where(created_at: from...to).size}
    end
    @book = Book.new
  end

  def create
    @book = current_user.books.new(book_params) 
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_comments.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= attachment_image_tag book_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: 'btn-sm btn-danger', method: :delete %></td>
    	<% end %>
    </tr>
  <% end %>
</table>
<%= form_with model:[book,book_comment], local: true do |f| %>
  <%= f.text_area :comment, size:"90x5" %><br>
  <%= f.submit '送信'%>
<% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group" id="star">
    <%= f.label :rate %>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

<script>
$('#star').raty({
  size     : 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  scoreName: 'book[rate]' ,
  half: false,
});
</script>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td id="favorites_buttons_<%= book.id %>">
          <%= render partial: 'favorites/favorites', locals: { book: book } %>
        </td>
        <td>コメント数: <%= book.book_comments.count %></td>
        <td>
          <td>
            <div id="star-rate-<%= book.id %>"></div>
              <script>
              $('#star-rate-<%= book.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                half      : false,
                readOnly: true,
                score: <%= book.rate %>,
              });
              </script>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
 <%= current_user.books.where("created_at >= ?", Time.zone.now.beginning_of_day).count %>
</div>
<div>
 <%= current_user.books.where(created_at: 1.day.ago.all_day).count %>
</div>
<div>
 <%= current_user.books.where(created_at: Time.current.all_week).count %>
</div>
<div>
 <%= current_user.books.where(created_at: Time.current.last_week.all_week).count %>
</div>

app/views/books/category.html.erb
<h1>aaa</h1>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
    	<%= form_with model: @book,local:true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
        <div class="form-group"  id = "star-rate-<%= @book.id %>"></div>
        <script>
          $('#star-rate-<%= @book.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            half: false,
            readOnly: true,
            score: <%= @book.rate %>,
            scoreName: 'book[rate]',
          })
        </script>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
        <%= link_to "新しい順", sort: 'created_at DESC' %> | <%= link_to "評価の高い順", sort: 'rate DESC' %>
        <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
        <tr>
          <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td id="favorites_buttons_<%= @book.id %>">
            <%= render partial: 'favorites/favorites', locals: { book: @book } %>
          </td>
          <td>
            <div id = "star-rate-<%= @book.id %>"></div>
            <script>
              $('#star-rate-<%= @book.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                half: false,
                readOnly: true,
                score: <%= @book.rate %>,
                scoreName: 'book[rate]',
              })
            </script>
          </td>
          <td>コメント数: <%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <div id="comments-area">
        <%= render "book_comments/book_comments",book: @book %>
      </div>
      <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
        <%= f.text_area :comment, size:"90x5" %><br>
        <%= f.submit '送信'%>
      <% end %>
    </div>
  </div>
</div>